-- RCPL Partner Platform — baseline schema (Oracle).
-- Enum-valued columns store the exact string values from the frontend contract
-- (src/types.ts) so the API and UI types stay aligned. Booleans are NUMBER(1) 0/1.
-- JSON payloads are held as CLOB (JSON text (de)serialized by the app).

-- ---------------------------------------------------------------------------
-- Identity & access
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
    code       VARCHAR2(32)  PRIMARY KEY,          -- ase_asm | finance | channel_dev | mdm | leadership | admin
    label      VARCHAR2(128) NOT NULL,
    color_var  VARCHAR2(64),
    blurb      VARCHAR2(512)
);

CREATE TABLE users (
    id            VARCHAR2(64)  PRIMARY KEY,
    name          VARCHAR2(200) NOT NULL,
    email         VARCHAR2(320) NOT NULL UNIQUE,
    role_code     VARCHAR2(32)  NOT NULL REFERENCES roles(code),
    region        VARCHAR2(64),
    state         VARCHAR2(64),
    is_active     NUMBER(1)     DEFAULT 1 NOT NULL,
    password_hash VARCHAR2(100) NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE role_screen_access (
    role_code   VARCHAR2(32)  NOT NULL REFERENCES roles(code),
    screen_path VARCHAR2(128) NOT NULL,             -- e.g. /leads, /approvals
    can_view    NUMBER(1)     DEFAULT 0 NOT NULL,
    can_manage  NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT pk_role_screen PRIMARY KEY (role_code, screen_path)
);

CREATE TABLE role_data_scope (
    role_code VARCHAR2(32) NOT NULL REFERENCES roles(code),
    entity    VARCHAR2(32) NOT NULL,                -- partners | gtm_coverage | dashboard | analytics
    scope     VARCHAR2(16) NOT NULL,                -- all | own_region | own_state
    CONSTRAINT pk_role_data_scope PRIMARY KEY (role_code, entity)
);

CREATE TABLE role_analytics_section (
    role_code VARCHAR2(32) NOT NULL REFERENCES roles(code),
    section   VARCHAR2(32) NOT NULL,                -- overview | detail | efficiency
    CONSTRAINT pk_role_analytics PRIMARY KEY (role_code, section)
);

-- ---------------------------------------------------------------------------
-- Partners
-- ---------------------------------------------------------------------------
CREATE TABLE partners (
    id             VARCHAR2(64)  PRIMARY KEY,        -- e.g. p4 or candidate:<id>
    legal_name     VARCHAR2(300) NOT NULL,
    partner_type   VARCHAR2(32)  NOT NULL,           -- distributor | vendor | logistics | copacker
    state          VARCHAR2(64),
    town           VARCHAR2(128),
    status         VARCHAR2(24)  NOT NULL,           -- in_review | active | discontinued
    onboarded_at   VARCHAR2(32),                     -- display date, e.g. '18 Jun 2022'
    discontinued_at VARCHAR2(32),
    db_code        VARCHAR2(32),                      -- e.g. DB-1187
    candidate_id   VARCHAR2(64)
);
CREATE INDEX ix_partners_state ON partners(state);
CREATE INDEX ix_partners_type  ON partners(partner_type);

-- ---------------------------------------------------------------------------
-- Candidates (lead pipeline)
-- ---------------------------------------------------------------------------
CREATE TABLE candidates (
    id                   VARCHAR2(64)  PRIMARY KEY,
    name                 VARCHAR2(300) NOT NULL,
    town                 VARCHAR2(128),
    db_category          VARCHAR2(128),
    turnover_monthly     NUMBER(12,2),
    expected_rcpl_turnover NUMBER(12,2),
    coverage_outlets     NUMBER(10),
    infra_score          NUMBER(4,1),
    fin_eval_pct         NUMBER(5,2),
    stage                VARCHAR2(24)  NOT NULL,       -- open|pending|approval_1|approval_2|active|rejected
    confidence_pct       NUMBER(5,2),
    is_best_match        NUMBER(1)     DEFAULT 0,
    user_created         NUMBER(1)     DEFAULT 0,
    created_by           VARCHAR2(32),                 -- role code
    created_at           NUMBER(19),                   -- epoch ms (drives SLA timer)
    source_intake_id     VARCHAR2(64),
    subtype              VARCHAR2(24),                  -- new | replacement | additional
    old_db_code          VARCHAR2(32),
    old_db_name          VARCHAR2(300),
    additional_reason    VARCHAR2(1000),
    discontinuation_form CLOB                           -- DisengagementForm as JSON text
);
CREATE INDEX ix_candidates_stage ON candidates(stage);

-- ---------------------------------------------------------------------------
-- Cases (approvals workflow) + child tables
-- ---------------------------------------------------------------------------
CREATE TABLE cases (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                     VARCHAR2(32)  NOT NULL UNIQUE,   -- CMP-#### / VND-####
    partner_name             VARCHAR2(300) NOT NULL,
    partner_type             VARCHAR2(32)  NOT NULL,
    town                     VARCHAR2(128),
    state                    VARCHAR2(64),
    subtype                  VARCHAR2(24)  NOT NULL,          -- new | replacement | additional
    status                   VARCHAR2(24)  NOT NULL,          -- draft|auto_cleared|flagged|approved|rejected
    owner_role               VARCHAR2(32)  NOT NULL,
    signoff_authority        VARCHAR2(8),                     -- SM | RBL
    sla_label                VARCHAR2(32),
    is_overdue               NUMBER(1)     DEFAULT 0 NOT NULL,
    has_discontinuation_form NUMBER(1)     DEFAULT 0 NOT NULL,
    discontinuation_form     CLOB,                            -- DisengagementForm as JSON text
    confidence_pct           NUMBER(5,2),
    flag_detail              VARCHAR2(2000),
    candidate_id             VARCHAR2(64),
    onboarding_notified      NUMBER(1)     DEFAULT 0 NOT NULL,
    created_at               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_cases_owner     ON cases(owner_role);
CREATE INDEX ix_cases_status    ON cases(status);
CREATE INDEX ix_cases_candidate ON cases(candidate_id);

CREATE TABLE case_involved_roles (
    case_id   NUMBER(19)   NOT NULL REFERENCES cases(id),
    role_code VARCHAR2(32) NOT NULL,
    CONSTRAINT pk_case_roles PRIMARY KEY (case_id, role_code)
);

CREATE TABLE case_finance_snapshot (
    case_id             NUMBER(19) PRIMARY KEY REFERENCES cases(id),
    own_funds           NUMBER(12,2),
    cc_limit            NUMBER(12,2),
    capital_available   NUMBER(12,2),
    required_investment NUMBER(12,2),
    funding_gap         NUMBER(12,2),
    readiness_pct       NUMBER(6,2)
);

CREATE TABLE case_channel_snapshot (
    case_id       NUMBER(19) PRIMARY KEY REFERENCES cases(id),
    score         NUMBER(4,1),
    threshold     NUMBER(4,1),
    gap           NUMBER(4,1),
    readiness_pct NUMBER(6,2)
);

CREATE TABLE case_finance_docs (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id   NUMBER(19)   NOT NULL REFERENCES cases(id),
    doc_key   VARCHAR2(64) NOT NULL,
    file_name VARCHAR2(300),
    data_url  CLOB,
    CONSTRAINT uq_case_finance_doc UNIQUE (case_id, doc_key)
);

CREATE TABLE case_channel_docs (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id   NUMBER(19) NOT NULL REFERENCES cases(id),
    file_name VARCHAR2(300)
);

CREATE TABLE case_notes_for_leadership (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id    NUMBER(19)    NOT NULL REFERENCES cases(id),
    author     VARCHAR2(200),
    body       VARCHAR2(2000),
    when_label VARCHAR2(32),
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- ---------------------------------------------------------------------------
-- Submitted documents
-- ---------------------------------------------------------------------------
CREATE TABLE submitted_documents (
    id           VARCHAR2(64)  PRIMARY KEY,
    case_code    VARCHAR2(32),
    partner_type VARCHAR2(32),
    doc_name     VARCHAR2(300) NOT NULL,
    claimed      VARCHAR2(1000),
    extracted    VARCHAR2(1000),
    status       VARCHAR2(24)  NOT NULL,             -- not_checked | pending | verified | mismatch
    file_name    VARCHAR2(300),
    uploaded_on  VARCHAR2(32),
    uploaded_at  VARCHAR2(32),
    verified_on  VARCHAR2(32),
    optional     NUMBER(1)     DEFAULT 0,
    this_week    NUMBER(1)     DEFAULT 0
);
CREATE INDEX ix_docs_case ON submitted_documents(case_code);

-- ---------------------------------------------------------------------------
-- Intake
-- ---------------------------------------------------------------------------
CREATE TABLE intake_items (
    id             VARCHAR2(64)  PRIMARY KEY,
    source         VARCHAR2(64),
    subject        VARCHAR2(500),
    received_at    VARCHAR2(64),
    partner_type   VARCHAR2(32),
    priority       VARCHAR2(24),
    region         VARCHAR2(64),
    summary        VARCHAR2(2000),
    confidence_pct NUMBER(5,2),
    engine         VARCHAR2(32),                      -- 'rules' (deterministic parser)
    raw_json       CLOB,
    processed      NUMBER(1)     DEFAULT 0 NOT NULL,
    candidate_id   VARCHAR2(64)
);
CREATE INDEX ix_intake_processed ON intake_items(processed);

CREATE TABLE intake_fields (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_id VARCHAR2(64)  NOT NULL REFERENCES intake_items(id),
    label     VARCHAR2(200),
    value     VARCHAR2(1000),
    ok        NUMBER(1)     DEFAULT 1
);

-- ---------------------------------------------------------------------------
-- Communication
-- ---------------------------------------------------------------------------
CREATE TABLE comm_threads (
    code         VARCHAR2(64)  PRIMARY KEY,
    town         VARCHAR2(128),
    partner_name VARCHAR2(300),
    audience     VARCHAR2(24),                        -- internal | partner
    last_message VARCHAR2(2000)
);

CREATE TABLE comm_messages (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_code    VARCHAR2(64)  NOT NULL REFERENCES comm_threads(code),
    author_role    VARCHAR2(32),
    author_name    VARCHAR2(200),
    body           VARCHAR2(2000),
    is_next_replier NUMBER(1)    DEFAULT 0,
    created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_comm_msg_thread ON comm_messages(thread_code);

-- ---------------------------------------------------------------------------
-- Grievances
-- ---------------------------------------------------------------------------
CREATE TABLE grievances (
    id          VARCHAR2(64)  PRIMARY KEY,
    distributor VARCHAR2(300) NOT NULL,
    town        VARCHAR2(128),
    category    VARCHAR2(128),
    summary     VARCHAR2(2000),
    owner_role  VARCHAR2(32),
    status      VARCHAR2(24)  NOT NULL,               -- open | in_progress | resolved
    sla_label   VARCHAR2(32),
    is_overdue  NUMBER(1)     DEFAULT 0 NOT NULL,
    raised_on   VARCHAR2(32)
);
CREATE INDEX ix_grievances_status ON grievances(status);

CREATE TABLE grievance_updates (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grievance_id VARCHAR2(64)  NOT NULL REFERENCES grievances(id),
    on_date      VARCHAR2(32),
    by_actor     VARCHAR2(200),
    note         VARCHAR2(2000)
);

-- ---------------------------------------------------------------------------
-- Notifications, audit, reports, GTM coverage
-- ---------------------------------------------------------------------------
CREATE TABLE notifications (
    id         VARCHAR2(64)  PRIMARY KEY,
    title      VARCHAR2(300),
    body       VARCHAR2(2000),
    href       VARCHAR2(256),
    for_role   VARCHAR2(32),
    is_read    NUMBER(1)     DEFAULT 0 NOT NULL,
    time_label VARCHAR2(64),
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_notif_role ON notifications(for_role);

CREATE TABLE audit_log (
    id         VARCHAR2(64)  PRIMARY KEY,
    when_label VARCHAR2(64),
    actor      VARCHAR2(200),
    kind       VARCHAR2(24),                          -- human | system
    action     VARCHAR2(1000),
    entity     VARCHAR2(200),
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_audit_created ON audit_log(created_at);

CREATE TABLE reports (
    id         VARCHAR2(64)  PRIMARY KEY,
    name       VARCHAR2(300) NOT NULL,
    format     VARCHAR2(24),
    date_label VARCHAR2(32),
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE gtm_coverage (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state           VARCHAR2(64),
    town            VARCHAR2(128),
    planned_outlets NUMBER(10),
    actual_outlets  NUMBER(10),
    gap             NUMBER(10)
);
CREATE INDEX ix_gtm_state ON gtm_coverage(state);
