-- Extended schema: template engine, per-user settings, onboarding/scoring config,
-- GTM coverage hierarchy, intake document overrides, and the candidate shortlist flag.
-- Replaces the flat gtm_coverage placeholder from V1 with a proper hierarchy.

DROP TABLE gtm_coverage;

-- ---------------------------------------------------------------------------
-- Template engine — partner types → required documents + approval workflow
-- ---------------------------------------------------------------------------
CREATE TABLE partner_types (
    code       VARCHAR2(32)  PRIMARY KEY,          -- distributor | vendor | logistics | copacker
    label      VARCHAR2(128) NOT NULL,
    is_active  NUMBER(1)     DEFAULT 1 NOT NULL,    -- false => "Coming soon"
    sort_order NUMBER(4)     DEFAULT 0
);

CREATE TABLE partner_type_documents (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type_code VARCHAR2(32)  NOT NULL REFERENCES partner_types(code),
    doc_name          VARCHAR2(200) NOT NULL,
    sort_order        NUMBER(4)     DEFAULT 0
);
CREATE INDEX ix_pt_docs ON partner_type_documents(partner_type_code);

CREATE TABLE partner_type_workflow (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type_code VARCHAR2(32)  NOT NULL REFERENCES partner_types(code),
    step              VARCHAR2(200) NOT NULL,
    sort_order        NUMBER(4)     DEFAULT 0
);
CREATE INDEX ix_pt_wf ON partner_type_workflow(partner_type_code);

-- ---------------------------------------------------------------------------
-- Per-user settings (My Settings)
-- ---------------------------------------------------------------------------
CREATE TABLE user_settings (
    user_id                VARCHAR2(64) PRIMARY KEY REFERENCES users(id),
    inbox_provider         VARCHAR2(24),                      -- gmail | outlook | null
    inbox_address          VARCHAR2(320),
    auto_forward_unmatched NUMBER(1)    DEFAULT 1 NOT NULL,
    sla_hours              NUMBER(5)    DEFAULT 24 NOT NULL
);

-- ---------------------------------------------------------------------------
-- Onboarding config / scoring thresholds + reference lists
-- ---------------------------------------------------------------------------
CREATE TABLE onboarding_config (
    config_key   VARCHAR2(64) PRIMARY KEY,
    config_value NUMBER(12,2) NOT NULL
);

CREATE TABLE db_category (
    code       VARCHAR2(64)  PRIMARY KEY,           -- e.g. 'GT DB (with CSO/DSM)'
    label      VARCHAR2(128) NOT NULL,
    sort_order NUMBER(4)     DEFAULT 0
);

CREATE TABLE infra_item (
    item_key   VARCHAR2(64)  PRIMARY KEY,           -- salesmen | delivery | ...
    label      VARCHAR2(200) NOT NULL,
    sort_order NUMBER(4)     DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- GTM coverage — state → city → area → DB hierarchy + factor definitions
-- ---------------------------------------------------------------------------
CREATE TABLE gtm_state (
    code   VARCHAR2(8)   PRIMARY KEY,
    name   VARCHAR2(128) NOT NULL,
    region VARCHAR2(24),                             -- North | South | East | West | Central
    target NUMBER(10)    DEFAULT 0,
    actual NUMBER(10)    DEFAULT 0
);

CREATE TABLE gtm_city (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_code VARCHAR2(8)   NOT NULL REFERENCES gtm_state(code),
    name       VARCHAR2(128) NOT NULL,
    target     NUMBER(10)    DEFAULT 0,
    actual     NUMBER(10)    DEFAULT 0
);
CREATE INDEX ix_gtm_city_state ON gtm_city(state_code);

CREATE TABLE gtm_area (
    id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id NUMBER(19)    NOT NULL REFERENCES gtm_city(id),
    name    VARCHAR2(128) NOT NULL,
    target  NUMBER(10)    DEFAULT 0,
    actual  NUMBER(10)    DEFAULT 0
);
CREATE INDEX ix_gtm_area_city ON gtm_area(city_id);

CREATE TABLE gtm_db (
    id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id NUMBER(19)    NOT NULL REFERENCES gtm_area(id),
    name    VARCHAR2(300) NOT NULL,
    db_type VARCHAR2(64),
    status  VARCHAR2(24)                             -- Active | In review
);
CREATE INDEX ix_gtm_db_area ON gtm_db(area_id);

CREATE TABLE gtm_factor (
    factor_key VARCHAR2(64)  PRIMARY KEY,
    label      VARCHAR2(200) NOT NULL,
    sub        VARCHAR2(200),
    icon       VARCHAR2(64),
    per_target NUMBER(10,3),
    delta      NUMBER(10,4),
    is_money   NUMBER(1)     DEFAULT 0,
    is_extra   NUMBER(1)     DEFAULT 0,
    sort_order NUMBER(4)     DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Intake document overrides (replaced docs in Intake Review)
-- ---------------------------------------------------------------------------
CREATE TABLE intake_doc_overrides (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_id VARCHAR2(64)  NOT NULL REFERENCES intake_items(id),
    doc_name  VARCHAR2(200) NOT NULL,
    file_name VARCHAR2(300),
    data_url  CLOB,
    CONSTRAINT uq_intake_doc UNIQUE (intake_id, doc_name)
);

-- ---------------------------------------------------------------------------
-- Candidate comparison shortlist flag (cross-persona shortlist)
-- ---------------------------------------------------------------------------
ALTER TABLE candidates ADD shortlisted NUMBER(1) DEFAULT 0 NOT NULL;
